name: ElanGuard
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.1.10=py_0
  - alabaster=0.7.10=py36_1
  - asn1crypto=0.24.0=py36_0
  - astor=0.6.2=py_0
  - astroid=1.6.3=py36_0
  - babel=2.5.3=py36_0
  - backcall=0.1.0=py_0
  - backports=1.0=py36_1
  - backports.weakref=1.0rc1=py36_1
  - blas=1.1=openblas
  - bleach=1.5.0=py36_0
  - boost=1.67.0=py36_0
  - boost-cpp=1.67.0=0
  - bzip2=1.0.6=1
  - ca-certificates=2018.4.16=0
  - cairo=1.14.10=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - cloudpickle=0.5.2=py_0
  - cryptography=2.2.1=py36_0
  - cycler=0.10.0=py36_0
  - dask-core=0.17.2=py_0
  - dbus=1.10.22=0
  - decorator=4.3.0=py_0
  - docutils=0.14=py36_0
  - doxygen=1.8.14=0
  - entrypoints=0.2.3=py36_1
  - expat=2.2.5=0
  - ffmpeg=3.2.4=3
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - gettext=0.19.8.1=0
  - gflags=2.2.1=0
  - giflib=5.1.4=0
  - glib=2.55.0=0
  - glog=0.3.5=0
  - gmp=6.1.2=0
  - gnutls=3.5.17=0
  - graphite2=1.3.11=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - h5py=2.7.1=py36_2
  - harfbuzz=1.7.6=0
  - hdf5=1.10.1=2
  - html5lib=0.9999999=py36_0
  - icu=58.2=0
  - idna=2.6=py36_1
  - imageio=2.3.0=py36_0
  - imagesize=1.0.0=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36_0
  - isort=4.3.4=py36_0
  - jasper=1.900.1=4
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36_1
  - lazy-object-proxy=1.3.1=py36_0
  - libffi=3.2.1=3
  - libgpuarray=0.7.5=0
  - libiconv=1.15=0
  - libidn11=1.33=0
  - libpng=1.6.34=0
  - libsodium=1.0.16=0
  - libtiff=4.0.9=0
  - libwebp=0.5.2=7
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - lmdb=0.9.21=0
  - m4=1.4.18=0
  - markdown=2.6.11=py_0
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mccabe=0.6.1=py36_0
  - mistune=0.8.3=py36_1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - nettle=3.3=0
  - networkx=2.1=py36_0
  - ninja=1.8.2=h2d50403_1
  - numpy=1.14.2=py36_blas_openblas_200
  - numpydoc=0.8.0=py36_0
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=7
  - opencv=3.4.1=py36_blas_openblas_200
  - openssl=1.0.2o=0
  - packaging=17.1=py_0
  - pandas=0.22.0=py36_0
  - pandoc=2.1.3=0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.0=py_0
  - patsy=0.5.0=py36_0
  - pcre=8.41=1
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.1.0=py36_0
  - pip=9.0.3=py36_0
  - pixman=0.34.0=1
  - prompt_toolkit=1.0.15=py36_0
  - protobuf=3.5.1=py36_3
  - psutil=5.4.5=py36_0
  - ptyprocess=0.5.2=py36_0
  - pycodestyle=2.4.0=py36_0
  - pycparser=2.18=py36_0
  - pyflakes=1.6.0=py36_0
  - pygments=2.2.0=py36_0
  - pylint=1.8.4=py36_0
  - pyopenssl=17.5.0=py36_1
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - pysocks=1.6.8=py36_1
  - python=3.6.5=1
  - python-dateutil=2.7.2=py_0
  - python-leveldb=0.193=py36_0
  - pytz=2018.4=py_0
  - pywavelets=0.5.2=py36_1
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_4
  - qt=5.6.2=7
  - qtawesome=0.4.4=py36_0
  - qtconsole=4.3.1=py36_0
  - qtpy=1.4.0=py36_0
  - readline=7.0=0
  - requests=2.18.4=py36_1
  - rope=0.10.7=py36_0
  - scikit-image=0.13.1=py36_0
  - scikit-learn=0.19.1=py36_blas_openblas_201
  - scipy=1.0.1=py36_blas_openblas_200
  - seaborn=0.8.1=py36_0
  - setuptools=39.0.1=py36_0
  - simplegeneric=0.8.1=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - snappy=1.1.7=1
  - snowballstemmer=1.2.1=py36_0
  - sphinx=1.7.2=py36_0
  - sphinxcontrib-websupport=1.0.1=py36_0
  - spyder=3.2.8=py36_0
  - sqlite=3.20.1=2
  - statsmodels=0.8.0=py36_0
  - termcolor=1.1.0=py36_1
  - testpath=0.3.1=py36_0
  - tk=8.6.7=0
  - toolz=0.9.0=py_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - werkzeug=0.14.1=py_0
  - wheel=0.31.0=py36_0
  - wrapt=1.10.11=py36_0
  - x264=20131217=3
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=0
  - cudatoolkit=8.0=3
  - cudnn=7.0.5=cuda8.0_0
  - cupti=8.0.61=0
  - gast=0.2.0=py36_0
  - grpcio=1.11.0=py36hf484d3e_0
  - intel-openmp=2018.0.0=8
  - keras-gpu=2.1.5=py36_0
  - leveldb=1.20=hf484d3e_1
  - libboost=1.65.1=habcd387_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libprotobuf=3.4.1=h5b8497f_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.2=1
  - nccl=1.3.4=cuda8.0_1
  - py-boost=1.65.1=py36hf484d3e_4
  - python-gflags=3.1.2=py36_0
  - pytorch=0.4.0=py36hd73e86b_0
  - tensorflow-gpu=1.5.0=0
  - tensorflow-gpu-base=1.5.0=py36had95abb_0
  - tensorflow-tensorboard=1.5.1=py36hf484d3e_0
  - pip:
    - colorama==0.3.9
    - cython==0.28.2
    - darkflow==1.0.0
    - dask==0.17.2
    - easydict==1.7
    - graphviz==0.8.3
    - imgaug==0.2.5
    - ipyparallel==6.1.1
    - ipywidgets==7.2.1
    - keras==2.1.5
    - mxnet-cu80==1.2.0b20180510
    - nose==1.3.7
    - notebook==5.4.1
    - opencv-python==3.4.0.12
    - pycocotools==2.0.0
    - send2trash==1.5.0
    - shapely==1.6.4.post1
    - tensorflow==1.5.0
    - terminado==0.8.1
    - terminaltables==3.1.0
    - torch==0.4.0
    - tqdm==4.23.4
    - widgetsnbextension==3.2.1
    - yolo34py-gpu==0.1rc12
prefix: /home/mtl/anaconda3/envs/ElanGuard

